[project]
name = "methods"
version = "0.1.0"
description = "Methods for cross interpolation"

[build-system]
build-backend = "flit_core.buildapi"
requires = ["flit_core >=3.4"]

[tool.pytest.ini_options]
markers = [
    "matrix",
]